### ISSUE TITLE
Layers not retained when switching from English to French site or vice-versa

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1657]
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley

**Steps to Reproduce**

- Load the English site
- Once all the layers are loaded, select "French" from the left side panel
- French Viewer loads. However, no layers are present

Clicking on "English" from this  French site loads back the English site with layers.

This issue is also seen when you load the viewer using French site url. Please investigate

![image](https://cloud.githubusercontent.com/assets/18539315/22521809/4c3e5c70-e887-11e6-8da4-2ab17958a28f.png)

**Comment by ChrisLatRNCan** [comment]
rc1 is working
http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Airports,Barley
rc2 has this error
```
TypeError: Cannot read property 'layerEntries' of undefined
    at http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/lib/core.js:48:11664
    at Array.map (native)
    at http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/lib/core.js:48:11558
    at l (http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/lib/core.js:3:4096)
    at http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/lib/core.js:3:4268
    at p.$eval (http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/lib/core.js:3:11789)
    at p.$digest (http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/lib/core.js:3:10297)
    at p.$apply (http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/lib/core.js:3:12072)
    at a (http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/lib/core.js:2:19086)
    at g (http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/lib/core.js:2:20934)
```

**Comment by bkutty** [comment]
Accepted as per tests on v1.5.0-rc3
