### ISSUE TITLE
Unable to import zipped shapefile

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2037]
Tested build: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html
Test data:[ne_10m_airports.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/1102652/ne_10m_airports.zip)

Importing  zipped shapefile gives an error of "incorrect format". Please investigate

![image](https://user-images.githubusercontent.com/18539315/27547123-ee8b6ef8-5a62-11e7-8e2e-3e4e45b405bc.png)

**Comment by AleksueiR** [comment]
Error:
> rv-main.js:94510 TypeError: proj4 is not a function
    at Function.shp.parseZip (rv-main.js:172268)
    at rv-main.js:172325
    at tryToUnwrap (rv-main.js:66267)
    at tryCatch (rv-main.js:66230)
    at Object.safelyResolveThenable [as safely] (rv-main.js:66270)
    at new Promise (rv-main.js:44626)
    at Function.shp.getShapefile (rv-main.js:172324)
    at shp (rv-main.js:172229)
    at Object.shapefile (rv-main.js:171102)
    at Object.validateFile (rv-main.js:171108) "Possibly unhandled rejection: {}"

**Comment by james-rae** [comment]
Using `webpack` now breaks our [shapefile library](https://github.com/calvinmetcalf/shapefile-js) . A similar problem to what we found in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2044 . 

Will fork the library, correct the `proj4` declaration and also a problem with the dbf loader, and use the fork.

**Comment by james-rae** [comment]
Considered finished once geoApi `v0.0.0-protoLR-71` or higher is consumed by the viewer

**Comment by AleksueiR** [comment]
Still getting errors:
> loaderFileDirective file type is wrong TypeError: data.readUInt8 is not a function
    at dbfHeader (http://localhost:6001/rv-main.js:180394:35)
    at module.exports (http://localhost:6001/rv-main.js:180457:16)
    at http://localhost:6001/rv-main.js:172264:15
    at Array.map (native)
    at Function.shp.parseZip (http://localhost:6001/rv-main.js:172253:23)
    at http://localhost:6001/rv-main.js:172305:19
    at tryToUnwrap (http://localhost:6001/rv-main.js:65969:5)
    at tryCatch (http://localhost:6001/rv-main.js:65981:17)
    at safelyResolveThenable (http://localhost:6001/rv-main.js:65972:16)
    at new Promise (http://localhost:6001/rv-main.js:65846:5)
    TypeError: data.readUInt8 is not a function
    at dbfHeader (http://localhost:6001/rv-main.js:180394:35)
    at module.exports (http://localhost:6001/rv-main.js:180457:16)
    at http://localhost:6001/rv-main.js:172264:15
    at Array.map (native)
    at Function.shp.parseZip (http://localhost:6001/rv-main.js:172253:23)
    at http://localhost:6001/rv-main.js:172305:19
    at tryToUnwrap (http://localhost:6001/rv-main.js:65969:5)
    at tryCatch (http://localhost:6001/rv-main.js:65981:17)
    at safelyResolveThenable (http://localhost:6001/rv-main.js:65972:16)
    at new Promise (http://localhost:6001/rv-main.js:65846:5) "Possibly unhandled rejection: {}"

**Comment by james-rae** [comment]
Very weird. It would fail last week without that `.buffer` property, and now it is the reverse.
Have backed out the change in our [shapefile library](https://github.com/fgpv-vpgf/shapefile-js) under `v3.6.0`

**Comment by james-rae** [comment]
New geoApi `v0.0.0-protoLR-76` has updated library reference.

**Comment by mweech** [comment]
@james-rae please estimate.
