### ISSUE TITLE
Service does not respond while importing service layers in IE11

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2054]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily09/prod/samples/index-samples.html
Tested data:
http://maps-cartes.ec.gc.ca/arcgis/rest/services/SpeciesProtectRestore_Canada_CanadianWildlifeService/MapServer/0

![image](https://user-images.githubusercontent.com/18723160/27595516-e3008dfc-5b2a-11e7-8162-d4f0f9a0cd84.png)

**Comment by milesap** [comment]
In IE, console posts the following error just before failure:

TypeError: Unable to get property 'toUpperCase' of undefined or null reference
   at Anonymous function (http://js.arcgis.com/3.20/:228:425)
   at Anonymous function (http://js.arcgis.com/3.20/:230:499)
   at Anonymous function (http://js.arcgis.com/3.20/:233:282)
   at fa (http://js.arcgis.com/3.20/:237:112)
   at c (http://js.arcgis.com/3.20/:213:325)
   at getLayers (http://localhost:6001/rv-main.js:181252:13)
   at Anonymous function (http://localhost:6001/rv-main.js:181279:13)
   at run (http://localhost:6001/ie-polyfills.js:16248:13)
   at Anonymous function (http://localhost:6001/ie-polyfills.js:16261:28)
   at flush (http://localhost:6001/ie-polyfills.js:12124:9) Possibly unhandled rejection: {"description":"Unable to get property 'toUpperCase' of undefined or null reference","number":-2146823281,"stack":"TypeError: Unable to get property 'toUpperCase' of undefined or null reference\n   at Anonymous function (http://js.arcgis.com/3.20/:228:425)\n   at Anonymous function (http://js.arcgis.com/3.20/:230

I removed all `toUpperCase` references in our code and the error persists. This is as far as ie would let me go.

**Comment by AleksueiR** [comment]
Just for the sake of sanity, can you try restoring old IE polyfills and see if it still breaks?

**Comment by milesap** [comment]
Same error on http://fgpv.cloudapp.net/demo/v2.0.0-daily07/dev/samples/index-mobile.html which was before Babel polyfills.
